version: 0.2
phases:
  install:
    commands:
      - pip install git-remote-codecommit
  build:
    commands:
       - env
       - git clone -b ${referenceName} codecommit::${region}://${repositoryName}
       - short_commitId=$(echo ${commitId} | cut -c1-8)
       - dt=$(date '+%d-%m-%Y-%H%M%S');
       - year=$(date '+%Y')
       - month=$(date '+%m')
       - today=$(date '+%d')
       - echo "$dt"
       - backup_file="$dt-${repositoryName}-${referenceName}-${short_commitId}-backup.zip" 
       - zip -yr  ${backup_file} ./
       - aws s3 cp ${backup_file} s3://${BACKUP_BUCKET}/${year}/${month}/${today}/